### PR TITLE
Setting to adjust height

### PR DESCRIPTION
**Pull request by Wyesumu**
PR for issue https://github.com/users/ArcaEge/projects/1/views/1?pane=issue&itemId=65229987

Noticed one bug that I was not able to resolve so far - if you make height as tall as possible and leave it with the default width then the bar is overflowing corners on small values if you enable rounded corners:
image

And if you make it extremely small then it looks really broken:

image

In CSS I would just enable overflow: hidden on the container but looks like here it does not work

### CODE REVIEW

**Comment by ArcaEge** [comment]
Yeah, that's why I marked it as experimental. I also thought of using a gradient with the stops very close to each other but turns out gradients also aren't supported. Anyway, thanks for the PR and I'll have a look at it when I get home (in ~1 hour)

**Comment by ArcaEge** [comment]
Sorry my train was delayed, I'll have a look now though

**Comment by ArcaEge** [comment]
Hello, the height wasn't updating for me, I had to remove the hardcoded heights from the CSS file. Apart from that, I've fixed a minor cosmetic bug (the inner border radius was set to 0.3 instead of 0.15 when circular borders were disabled, causing it to have a different curvature, see image below for what I mean).
image
Other than that, I've also changed the measurement for the bar height to tenth of an em instead of fifth, to allow for more precise control over it. As a result, I've also changed the default value to 0.9em height and made the min height 0.2em since below that, the bar is invisible.

**Comment by ArcaEge** [comment]
I've submitted it, it should be live by tomorrow

**Comment by ArcaEge** [comment]
It's live now

**Comment by Wyesumu** [comment]
@ArcaEge Forgot about the screenshot. Will keep it in mind, thank you!

**Comment by ArcaEge** [comment]
Thanks!

**Pull request merged**
