### PR TITLE
Calculate progress based on period and not % of day

### PR DESCRIPTION
**Pull request by Wyesumu**
By default, it works the same way as it is now - it shows % of day progress (period from 00:00 to 23:59) but now user can adjust period to his own. For example, from 9:00 to 18:00 to track progress of his workday.

### CODE REVIEW

**Comment by ArcaEge** [comment]
Thanks, I'll have a look over the code!

**Comment by ArcaEge** [comment]
Code looks good, I'll do a bit of testing and then submit it.

**Comment by ArcaEge** [comment]
Looks good to me, though I need to update the defaults.

**Comment by ArcaEge** [comment]
Thanks, merged!

**Comment by ArcaEge** [comment]
Hello, upon further testing I've realised that the code doesn't handle wrap around midnight correctly (for example if reset time is past midnight). I'll be updating it before I submit the extension again (yes I shouldn't be using the main branch for this) but anyway, thank you!

**Comment by ArcaEge** [comment]
I've uploaded it, waiting for approval
image

**Comment by Wyesumu** [comment]
Thank you for noticing it and fixing, I missed that part. And also sorry for missed log line

**Comment by ArcaEge** [comment]
They probably would've allowed the log as it's probably not that excessive but it's better to not add additional lines to the log every second - it makes filtering through them easier

**Comment by Wyesumu** [comment]
For sure, I was removing all log entries but missed that line for some reason

**Comment by ArcaEge** [comment]
Also, if you occasionally have time to work on it, would you like me to add you as a collaborator?

**Comment by Wyesumu** [comment]
Yeah, I could. Do you have a roadmap/to do list of stuff that you want to implement in this extension?

**Comment by ArcaEge** [comment]
Ok, I'm currently outside but I'll do all that once I get back home in a few hours (if I hopefully don't forget)

**Comment by ArcaEge** [comment]
Done, I need you to accept the invite.

**Comment by ArcaEge** [comment]
I'll create a GH project with a todo list with features to implement, give me a few mins

**Comment by ArcaEge** [comment]
Done, I've added a few feature requests.

**Pull request merged**
